### ISSUE TITLE
简单调用API，报JSONDecodeError错误

### ISSUE THREAD

**Issue by Mingwang1986** [akfamily/awesome-data-show#5]
原始代码：
import akshare as ak
ak.stock_hot_rank_wc(date='20230110')

报错：
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/var/folders/1h/c_nwv_tj1nqgvhwrzpzdxj5r0000gn/T/ipykernel_35310/4290076817.py in <module>
      1 # _*_ coding:UTF-8 _*_
----> 2 ak.stock_hot_rank_wc(date='20230110')
      3 

~/.local/lib/python3.8/site-packages/akshare/stock_feature/stock_wencai.py in stock_hot_rank_wc(date)
     64         })
     65         r = requests.post(url, data=params, headers=headers)
---> 66         data_json = r.json()
     67         temp_df = pd.DataFrame(
     68             data_json["data"]["answer"][0]["txt"][0]["content"]["components"][0][

~/anaconda3/anaconda3/lib/python3.8/site-packages/requests/models.py in json(self, **kwargs)
    908                     # used.
    909                     pass
--> 910         return complexjson.loads(self.text, **kwargs)
    911 
    912     @property

~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    523             parse_constant is None and object_pairs_hook is None
    524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
    526     if cls is None:
    527         cls = JSONDecoder

~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

我就是多次调用这个接口，难道是这个接口有调用次数的限制吗？

**Comment by albertandking** [comment]
> 原始代码： import akshare as ak ak.stock_hot_rank_wc(date='20230110')
> 
> ## 报错：
> JSONDecodeError Traceback (most recent call last) /var/folders/1h/c_nwv_tj1nqgvhwrzpzdxj5r0000gn/T/ipykernel_35310/4290076817.py in 1 # _*_ coding:UTF-8 _*_ ----> 2 ak.stock_hot_rank_wc(date='20230110') 3
> 
> ~/.local/lib/python3.8/site-packages/akshare/stock_feature/stock_wencai.py in stock_hot_rank_wc(date) 64 }) 65 r = requests.post(url, data=params, headers=headers) ---> 66 data_json = r.json() 67 temp_df = pd.DataFrame( 68 data_json["data"]["answer"][0]["txt"][0]["content"]["components"][0][
> 
> ~/anaconda3/anaconda3/lib/python3.8/site-packages/requests/models.py in json(self, **kwargs) 908 # used. 909 pass --> 910 return complexjson.loads(self.text, **kwargs) 911 912 @Property
> 
> ~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/**init**.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw) 523 parse_constant is None and object_pairs_hook is None 524 and not use_decimal and not kw): --> 525 return _default_decoder.decode(s) 526 if cls is None: 527 cls = JSONDecoder
> 
> ~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py in decode(self, s, _w, _PY3) 368 if _PY3 and isinstance(s, bytes): 369 s = str(s, self.encoding) --> 370 obj, end = self.raw_decode(s) 371 end = _w(s, end).end() 372 if end != len(s):
> 
> ~/anaconda3/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3) 398 elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf': 399 idx += 3 --> 400 return self.scan_once(s, idx=_w(s, idx).end())
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 我就是多次调用这个接口，难道是这个接口有调用次数的限制吗？

请注意调用的频率
